---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "omni.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "omni.labels" . | nindent 4 }}
    app.kubernetes.io/component: omni
    {{- with .Values.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.deployment.annotations | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels: {{- include "omni.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- if .Values.deployment.podAnnotations }}
      annotations:
      {{- toYaml .Values.deployment.annotations | nindent 6 }}
    {{- end }}
      labels: 
      {{- include "omni.labels" . | nindent 8 }}
      app.kubernetes.io/component: omni
      {{- with .Values.deployment.labels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: omni
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        resources:
          {{- with .Values.resources }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
        ports:
          - name: api
            containerPort: {{ .Values.service.api.port }}
            protocol: TCP
          - name: siderolink
            containerPort: {{ .Values.service.siderolink.api.port }}
            protocol: TCP
          - name: wireguard
            containerPort: {{ .Values.service.siderolink.wireguard.port }}
            protocol: UDP
          - name: event-sink
            containerPort: {{ .Values.service.eventSink.port }}
            protocol: TCP
          - name: k8s-proxy
            containerPort: {{ .Values.service.k8sProxy.port }}
            protocol: TCP
        resources:
          limits:
            squat.ai/tun: 1
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
            add:
              - NET_ADMIN
        volumeMounts:
          - name: tls
            mountPath: {{ .Values.volumeMounts.tls.mountPath }}
            readOnly: {{ .Values.volumeMounts.tls.readOnly }}
          - name: omni-asc
            mountPath: {{ .Values.volumeMounts.omniAsc.mountPath }}
            subPath: {{ .Values.volumeMounts.omniAsc.subPath }}
            readOnly: {{ .Values.volumeMounts.omniAsc.readOnly }}
        args:
          {{- include "omni.args" . | nindent 10 }}
      volumes:
        - name: tls
          secret:
            secretName: {{ .Values.volumes.tls.secretName }}
        - name: omni-asc
          secret:
            secretName: {{ .Values.volumes.gpg.secretName }}
